### ISSUE TITLE
Make with multiple jobs doesn't work

### ISSUE THREAD

**Issue by jemarinheiro** [KaiNorberg/PatchworkOS#13]
I tried `make setup all -j8`, and it didn't work. The image `PatchworkOS.img` was not located in the `bin` directory. Only single-job Make worked. I am using GNU Make 4.3, and the repo I cloned is at the newest commit (35ef9f9).

**Comment by KaiNorberg** [comment]
Thank you for reporting this. It was caused by the deploy target not having any prerequisites so when running with multiple jobs, the deploy target could be run before the project had finished building, this has been fixed.
